// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT92EHV6lr0w6iyYNaLL7pS0GSyIFeQrQ',
    appId: '1:233066248682:web:6f4ec0ce7e7ca68bf29a93',
    messagingSenderId: '233066248682',
    projectId: 'mini-kahoot-5974f',
    authDomain: 'mini-kahoot-5974f.firebaseapp.com',
    storageBucket: 'mini-kahoot-5974f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfzixMIEeiqmbqs--Mj1tpzYJcVEk_Kc',
    appId: '1:233066248682:android:db9383a906b005e5f29a93',
    messagingSenderId: '233066248682',
    projectId: 'mini-kahoot-5974f',
    storageBucket: 'mini-kahoot-5974f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0JPBth6Iq4vtGy0HGabAIZ2DaMX925sY',
    appId: '1:233066248682:ios:a297d13dce058ed1f29a93',
    messagingSenderId: '233066248682',
    projectId: 'mini-kahoot-5974f',
    storageBucket: 'mini-kahoot-5974f.firebasestorage.app',
    iosBundleId: 'com.example.miniKahootTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0JPBth6Iq4vtGy0HGabAIZ2DaMX925sY',
    appId: '1:233066248682:ios:a297d13dce058ed1f29a93',
    messagingSenderId: '233066248682',
    projectId: 'mini-kahoot-5974f',
    storageBucket: 'mini-kahoot-5974f.firebasestorage.app',
    iosBundleId: 'com.example.miniKahootTeacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT92EHV6lr0w6iyYNaLL7pS0GSyIFeQrQ',
    appId: '1:233066248682:web:d80ae1449406ef92f29a93',
    messagingSenderId: '233066248682',
    projectId: 'mini-kahoot-5974f',
    authDomain: 'mini-kahoot-5974f.firebaseapp.com',
    storageBucket: 'mini-kahoot-5974f.firebasestorage.app',
  );
}
